import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import {lightTheme} from "./myTheme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{height:"100%"}}>
      <body style={{height:"100%"}}>
        <ThemeProvider theme={lightTheme}>
            {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
