import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import {lightTheme} from "./myTheme";
import { CssBaseline } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{height:"100%"}}>
      <body>
        <ThemeProvider theme={lightTheme}>
          <CssBaseline>
            {children}
          </CssBaseline>
        </ThemeProvider>
      </body>
    </html>
  );
}
